repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.7.4'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]
        types: [python]
      - id: ruff-format
        types: [python]
  - repo: local
    hooks:
      - id: mypy
        name: Check mypy
        entry: mypy --namespace-packages -p camel_database_agent -p tests
        language: python
        types: [python]
        pass_filenames: false
        require_serial: true
        always_run: true
        verbose: true