name: Python application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'
    
    - name: Cache virtual environment
      uses: actions/cache@v3
      with:
        path: .venv
        key: venv-${{ runner.os }}-python-${{ hashFiles('pyproject.toml') }}
        restore-keys: |
          venv-${{ runner.os }}-python-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv ruff mypy
        uv venv .venv --python=3.10
        uv pip install -e ".[dev,test]"
    
    - name: Lint
      run: |
        source .venv/bin/activate
        make lint
    
    - name: Run tests
      run: |
        source .venv/bin/activate
        make tests